chore: prettify names
0xsquid/squid-types pull request #10
Opened 2024-01-03 06:14 UTC by ecdsafu

# Description of changes

Adds pretty names to wrappers, dexes and bridges

- closes ticket #

# Check specifically for:

WRITE_HERE

2024-01-29 22:20 UTC, jmdev3 commented on src/dexes/index.ts
> -  ALGEBRA = "algebra",
are we sure about this change?

2024-01-29 22:21 UTC, jmdev3 commented on src/dexes/index.ts
> +
are we sure about this change?

2024-01-29 22:22 UTC, jmdev3 commented on src/bridges/index.ts
> +export enum BridgeIcon {
we should add this on the config, not here as it's a type package

2024-01-29 22:22 UTC, jmdev3 commented on src/dexes/index.ts
> +export enum DexIcon {
same as above

2024-01-29 22:22 UTC, jmdev3 requested changes
leave some comments

2024-02-05 04:57 UTC, ecdsafu commented on src/dexes/index.ts
> +
No this is a mistake. DexType should not be deleted.

2024-03-22 20:35 UTC, closed without merging